### ISSUE TITLE
API Change Proposal 

### ISSUE THREAD

**Issue by appcypher** [Lord-sarcastic/lazerpay-rust-sdk#13]
Right now, Lazerpay Rust SDK looks so much like the node SDK. The issue with that is the library doesn't take full advantage of Rust's type safety all in the spirit of staying true to the official implementation. But node is not Rust. JavaScript is a weakly typed language.

For the reasons stated above, I would like to propose a slightly different, more Rusty interface for the SDK. Specifying it in a way that doesn't diverge too much from the reference implementation.

I think it will help with creating a more solid foundation for the project as Lazerpay grows its features.  

```rs
let lazerpay = Lazerpay::new()?; // Sets up API keys. Grabs details from .env.

let payment = lazerpay.create_payment(PaymentConfig { // Returns a payment object but doesn't send req.
    customer: Customer::new("Lagbaja Ajanaku", "lagbaja.ajanaku@gmail.com"),
    coin: Coin::USDC,
    currency: Currency::NGN,
    amount: 5_000,
    pk_address: "0x16227d60f7a0e586c66b005219dfc887d13c9531",
    reference: "Just sending some money your way",
    ..Default::default()
})?;

payment.send()?; // Sends payment req.

payment.check_confirmation()?; // Asks for confirmation.

payment.get_accepted_coins()?; // Get supported coins.
```

Let me know what you think and if there is any edge case I'm missing.

**Comment by Lord-sarcastic** [comment]
@ECJ222 see what I was saying.

I fully agree with your point @appcypher. We had this in mind and decided it to be the next iteration. We pushed the current API because of time constraints.

Constraints may exist in terms of hard coding the `Coin` enum. It seems that the Lazerpay documentation is undergoing incremental updates despite it being a `v1` API. I suggest we just have types that expect certain fields and we can cast responses into those types like so:
```rust
struct Coin {
    id: String
    name: String,
    symbol: String
    logo: Url,
}
```
and so on, so we can return arrays like: `[Coin]`

**Comment by appcypher** [comment]
Yeah that works, but I still recommend restricting the allowed value like this,

```rs
pub struct CoinInfo {
    pub name: String,
    pub symbol: String
    pub logo: Url,
    pub id: String
}

impl CoinInfo {
    pub fn new(...) -> Self {
        Self { ... }
    }
}

mod Coin {
    use crate::CoinInfo;
    
    pub const USDC: CoinInfo = CoinInfo::new(...);
    pub const BNB: CoinInfo = CoinInfo::new(...);
    pub const BTC: CoinInfo = CoinInfo::new(...);
    // ...
}

// And it can be used like this.
let coin = Coin::USDC;
```

The point of the enum was to allow only valid values for `Coin`.  The const exprs serve the same purpose here.

**Comment by ECJ222** [comment]
That makes sense @appcypher, We will add it in our next build.

Thank you for your contributions.

**Comment by appcypher** [comment]
I would love to but I've gotten so busy recently. How about a pair programming session this weekend (if you are available)?

**Comment by Lord-sarcastic** [comment]
Saturday is my birthday 😃 Don't want to code then, @ECJ222 can you show up?

**Comment by ECJ222** [comment]
Sure!
